(Maint) Suppress spec test output
The macosx_spec ensures that an error is raised when parsing invalid
XML, but this causes the following output when running the tests

  Fatal error: error parsing attribute name at :1.
  Fatal error: attributes construct error at :1.
  Fatal error: Couldn't find end of Start Tag bad line 1 at :1.
  Fatal error: Extra content at the end of the document at :1.

This commit suppresses the output written to STDERR. See
LibXML::XML::Error::VERBOSE_HANDLER.