(#22060) Revert "Faster MAC address load on Linux via sysfs"
This reverts commit 4b926d0df3bb02a0492908fd13479e0a148ae19e.
Author: Daniel Pittman daniel@puppetlabs.com
Date: Thu Jul 19 19:11:46 2012

While running `puppet agent --no-daemonize --debug`, and IFF somewhere in the
code I have $DEBUG = true, then if I Ctrl-C to kill the agent I see the
following exception:

  Exception `NilClass' at .../facter/lib/facter/macaddress.rb:19 -
  undefined local variable or method `path' for :Facter::Util::Resolution

This is followed by an "infinite" recursion / stackoverflow which impeeds
debugging other issues.

The enhancement introduced in 4b926d0 never actually took effect because this
exception was normally ignored causing the new (faster) MAC detection code to
always return nil. Spec tests were never written for this enhancement nor for
its interaction with ifconfig based MAC detection. Thus the safest path forward
is to just revert the offending commit.