(FACT-1819) Keep libfacter load failure backtrace
 - When libfacter is not found, append to the message the message from
   the rescued exception.

   Furthermore, preserve the backtrace from the original exception.

   That changes a previous message like:

   LoadError: new message

   To one that preserves more information like this instead:

   LoadError: new message
   cannot load such file -- /invalid/file/path
   from /usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'